"""Add abstract model

Revision ID: 4995fa08de6e
Revises: e0719e47acf9
Create Date: 2024-12-09 21:03:48.219871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4995fa08de6e'
down_revision = 'e0719e47acf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
